### ISSUE TITLE
你的博客，注册账号不能成功，我有问题就在这问了，看到帮我解答一下呀

### ISSUE THREAD

**Issue by chinafuhai** [onewe/RedisDesktopManager-Mac#1]
macdeployqt，这个怎么使用呢，我参考网上的文章，macdeployqt rdm.app ../../../src/qml/，运行后，rdm.app就一直闪退，后来打开包，从里面年到原因是因为This application faile
d to start because it could not find or load the Qt platform plugin "cocoa"，能不能给指导一下呢？

**Comment by onewe** [comment]
怎么复现,我看看问题.

**Comment by onewe** [comment]
其实我才接触QT 没多久 多多交流一下

**Comment by chinafuhai** [comment]
就是按你的blog上进行打包，完了后我想把生成的rdm.app（这时rdm.app大小为4M左右）想让别人来使用，这时就需要把依赖的包加进去，我就使用方法，macdeployqt rdm.app ../../../src/qml/进行加入，加入后这时rdm.app大小为50M左右。

这时我再运行rdm.app就无法运行，一直闪退。然后我打开rdm.app包的内容，发现里面有个文件夹macOS，里面有个脚本我再运行，发现报错为：This application faile
d to start because it could not find or load the Qt platform plugin "cocoa"。

**Comment by chinafuhai** [comment]
@onewe ，加你的QQ了，麻烦通过一下哈。我的qq是380499422
