### ISSUE TITLE
出新版了，再打个包呗：）

### ISSUE THREAD

**Issue by liheeng** [onewe/RedisDesktopManager-Mac#10]
如题

**Comment by onewe** [comment]
可以

**Comment by of0** [comment]
@onewe 催更，大佬～

**Comment by roamerxv** [comment]
@onewe 催更。大佬！

**Comment by long2ice** [comment]
@onewe 催更。大佬！

**Comment by onewe** [comment]
五一 五一 现在有点忙,大佬们.

**Comment by CodingOX** [comment]
@onewe 想请你喝杯咖啡噢！

**Comment by onewe** [comment]
@liheeng @of0 @roamerxv @long2ice 打了个包试一试.

**Comment by refeccd** [comment]
3q~

**Comment by refeccd** [comment]
> @liheeng @of0 @roamerxv @long2ice 打了个包试一试.

想请问下，这个版本还是不能通过 ssh 隧道连接 redis 吗

**Comment by onewe** [comment]
@liaozan 不支持 0.9.8 是支持的

**Comment by xiaobaiyouxi** [comment]
Connection error: QRedisClient compiled without ssh support. 
ssh还是不支持

**Comment by wdkGitHub** [comment]
@onewe  新版中文不可以吗？边框颜色在案模式下也感觉怪怪的

**Comment by zcleee** [comment]
中文用不了，界面感觉有点歪歪的，退回0.98了。还是非常感谢大佬的打包，辛苦了！

**Comment by onewe** [comment]
@xifengyema  我去打个支持ssh的包.LOL

**Comment by refeccd** [comment]
> @xifengyema 我去打个支持ssh的包.LOL

感谢！！
