### ISSUE TITLE
RDM 2019 Connection error: QRedisClient compiled without ssh support. 

### ISSUE THREAD

**Issue by briannguyen91** [onewe/RedisDesktopManager-Mac#12]

**Comment by onewe** [comment]
@briannguyen91 Since 0.9.9 RDM by default does not include SSH Tunneling support. You can create a SSH tunnel to your Redis server manually and connect to localhost: ssh -L 6379:REDIS_HOST:6379 SSH_USER@SSH_HOST -P SSH_PORT -i SSH_KEY -T -N
