### ISSUE TITLE
有没有能ssh登录的呀

### ISSUE THREAD

**Issue by newgoo** [onewe/RedisDesktopManager-Mac#18]
能帮忙搞一个有一个ssh代理的嘛？辛苦了

**Comment by onewe** [comment]
ssh 需要付费的,0.0.官方要恰饭

**Comment by willin** [comment]
Connection error: QRedisClient compiled without ssh support.

不是在编译的时候加入什么参数即可吗？

**Comment by willin** [comment]
https://github.com/uglide/qredisclient/blob/master/src/qredisclient/connection.cpp#L413-L418

需要定义 SSH_SUPPORT 变量， 引入 `include "sshtransporter.h"` 文件。大概是这么个意思，c++不是很懂
