### ISSUE TITLE
希望hub主 能持续更新

### ISSUE THREAD

**Issue by fqdeng** [onewe/RedisDesktopManager-Mac#2]
编译实在是太痛苦了，各种环境报错，很浪费时间

up主可以上一个支付宝，我赞助一杯咖啡☕️

**Comment by onewe** [comment]
也行 尽量跟上官方的版本节奏,总感觉对不住官方. @jonwinters

**Comment by fqdeng** [comment]
@onewe  没有对不住的，开源本来就允许二次分发嘛  搭建维护编译环境也是一种工作  可惜Mac编译 没有docker 之类的环境构建工具

**Comment by onewe** [comment]
@jonwinters 更新了一个版本 你看运行正常不,我打算出个脚本 自动打包

**Comment by Bodil-X** [comment]
> @jonwinters 更新了一个版本 你看运行正常不,我打算出个脚本 自动打包

我下载了，可以正常用

**Comment by onewe** [comment]
@Bodil-X ok,感谢反馈.
