### ISSUE TITLE
new 2020.1

### ISSUE THREAD

**Issue by lzysuqianqiu** [onewe/RedisDesktopManager-Mac#24]

**Comment by onewe** [comment]
ok,update soon

**Comment by onewe** [comment]
I have already updated this.
Can you try it?
Please.
@lzysuqianqiu

**Comment by lzysuqianqiu** [comment]
@onewe  I will try it when go back home

**Comment by onewe** [comment]
Thank you! @lzysuqianqiu

**Comment by onewe** [comment]
emmm,都是国人,..不装了。。。*´∀`)´∀`)*´∀`)*´∀`)哈

**Comment by lzysuqianqiu** [comment]
can you provide a installation version

**Comment by onewe** [comment]
@lzysuqianqiu i'm sorry,What a pity.
