### ISSUE TITLE
10.5.5 用不了

### ISSUE THREAD

**Issue by cuibty** [onewe/RedisDesktopManager-Mac#25]

**Comment by onewe** [comment]
@cuibty 描述一下,系统版本以及软件版本

**Comment by cuibty** [comment]
mac os 10.5.5

v2020.1-ci

**Comment by onewe** [comment]
这个是用不了的,要么升级一下 系统,要么使用低版本.

**Comment by cuibty** [comment]
10.5.5 不是最新的系统了么，还怎么升级？？？

**Comment by onewe** [comment]
@cuibty 我目前的系统功版本是10.12.6 也一样的用不了 最新的应该是15吧

**Comment by cuibty** [comment]
@onewe 最新的 mac os 是 10.5.5

**Comment by onewe** [comment]
![image](https://user-images.githubusercontent.com/38708836/86867162-eab54680-c104-11ea-8343-c30cf59f93bc.png)
@cuibty

**Comment by CodingOX** [comment]
> @onewe 最新的 mac os 是 10.5.5

你的是10.15.5 吧。。。
