### ISSUE TITLE
10.15.5无法使用

### ISSUE THREAD

**Issue by wxj-finbee** [onewe/RedisDesktopManager-Mac#26]
本地环境：
```
xjetry@iMac ~ % which python3
/Library/Frameworks/Python.framework/Versions/3.8/bin/python3
```

错误报告：
Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/Python
  Referenced from: /Applications/Redis Desktop Manager.app/Contents/MacOS/Redis Desktop Manager
  Reason: image not found

**Comment by wxj-finbee** [comment]
根据错误信息 加了个软连接可用了，但是可否从根本上解决呀
```
mkdir -p /usr/local/opt/python/Frameworks/Python.framework/Versions/
ln -s /Library/Frameworks/Python.framework/Versions/3.8 /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7
```

**Comment by onewe** [comment]
@wxj-finbee 我去改改脚本,主要是我本地系统没有升级 没有测试过,尴尬0.0

**Comment by onewe** [comment]
@wxj-finbee 提个PR?

**Comment by mengdodo** [comment]
@onewe @wxj-finbee 系统版本10.15.6 (19G2021) ，我用conda安装的python多版本。
现在本地默认 `/Users/用户名/anaconda3/bin/python`，按照上面的方法
```ln -s /Users/用户名/anaconda3/envs/py37 /usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7```
还是报错
```
Library not loaded: /usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/Python
Referenced from: /Users/USER/Downloads/*/Redis Desktop Manager.app/Contents/MacOS/Redis Desktop Manager
Reason: image not found
```
这个Python下面应该是什么目录啊, 我现在看到的 /Users/用户名/anaconda3/envs/py37
```
total 0
drwxr-xr-x   64 用户名  staff   2.0K  8  3 10:49 bin
drwxr-xr-x   19 用户名  staff   608B  8  3 10:49 conda-meta
drwxr-xr-x  113 用户名  staff   3.5K  8  3 10:49 include
drwxr-xr-x   89 用户名  staff   2.8K  8  3 10:49 lib
drwxr-xr-x    8 用户名  staff   256B  8  3 10:49 share
drwxr-xr-x    9 用户名  staff   288B  8  3 10:49 ssl
```

**Comment by chenpenghuan** [comment]
我这里是
ln -s /usr/local/opt/python3/Frameworks/Python.framework/Versions/3.8 /usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7

**Comment by mengdodo** [comment]
> 我这里是
> ln -s /usr/local/opt/python3/Frameworks/Python.framework/Versions/3.8 /usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7

谢谢，解决了我的问题😄
