### ISSUE TITLE
windows版

### ISSUE THREAD

**Issue by FuckDoctors** [onewe/RedisDesktopManager-Mac#27]
参考了一些资料写了一个windows版，需要的话可以加个链接。
[https://github.com/FuckDoctors/rdm-builder](https://github.com/FuckDoctors/rdm-builder) 
为了方便，改成了可以同时编译win和macOS了。

**Comment by onewe** [comment]
@FuckDoctors ok

**Comment by onewe** [comment]
@FuckDoctors 老哥打算长期维护吗？

**Comment by FuckDoctors** [comment]
> @FuckDoctors 老哥打算长期维护吗？

不懂qt和python编译的不对，windows的打不开，尴尬了。。。

昨天发现已经有windows的了：
https://github.com/lework/RedisDesktopManager-Windows

**Comment by FuckDoctors** [comment]
windows版加了嵌入式版本的python37.zip可以使用了，不知道还有没有其他问题。
已知不支持多语言。
欢迎指导~
