### ISSUE TITLE
0.9.8  mac 10.14 无法打来

### ISSUE THREAD

**Issue by JayeZhang** [onewe/RedisDesktopManager-Mac#3]
mac os majove  10.14 (18A391) 0.9.8版本无法打开

**Comment by onewe** [comment]
@JayeZhang 有没有错误信息,能否留下联系方式?

**Comment by JayeZhang** [comment]
jiezhang9306@sina.com  提示：“rdm.app” can’t be opened because the identity of the developer cannot be confirmed. “rdm.app” is on the disk image “rdm.dmg”. Chrome downloaded this disk image today at 11:09 from github.com.

**Comment by onewe** [comment]
@JayeZhang  https://jingyan.baidu.com/article/f71d60377960651ab741d140.html 看看是不是这种情况

**Comment by JayeZhang** [comment]
是这样的情况，但是我的的任何来源已经开启，并且RDM 0.9.5打开正常

**Comment by onewe** [comment]
@JayeZhang 好的,我今天晚上升级 系统试一试🤣🤣🤣🤣🤣🤣

**Comment by onewe** [comment]
@JayeZhang 我升级到10.14,是能正常使用的.

**Comment by Bodil-X** [comment]
> @JayeZhang 我升级到10.14,是能正常使用的.

我也升级到10.14了，也没问题

**Comment by paytham** [comment]
无法打开“rdm.app”，因为无法确认开发者的身份。同样的问题macos10.14

**Comment by onewe** [comment]
@paytham mac 系统的安全设置,系统设置->安全性与隐私->通用->点击"任要打开rdm"

**Comment by paytham** [comment]
@onewe 已经运行过sudo spctl --master-disable，0.98不行，0.95可以，不太懂mac应用的这种开发和编译，提供不了多余的帮助，抱歉

**Comment by Awezome** [comment]
打开应用程序文件夹，找到要打开的应用，然后按着键盘上面的control键，右键打开。
