### ISSUE TITLE
0.99忘记打包openssl依赖了

### ISSUE THREAD

**Issue by tyong920** [onewe/RedisDesktopManager-Mac#6]
麻烦重新编译一下，不胜感激🙏

**Comment by onewe** [comment]
@tyong920 好的，我以为去掉了openssl的依赖了。。没检查。不好意思了。

**Comment by onewe** [comment]
@tyong920 我检查了一下,编译出来的二进制文件没有依赖openssl.请问你这边报什么错呢??

**Comment by hedroid** [comment]
不能通过ssh连接

**Comment by onewe** [comment]
@hedroid 这就尴尬了.😅😅😅😅😅😅😅我重新弄一下

**Comment by onewe** [comment]
@hedroid [容我解释一下,官方说从0.9.9开始就不支持ssh连接](http://docs.redisdesktop.com/en/latest/install/#build-from-source)

**Comment by hedroid** [comment]
🙏
这么有用的功能给砍掉了。是不是放到付费版了呢。

**Comment by onewe** [comment]
@hedroid 可以去嫖0.9.8 那个版本,那个版本有保留这个功能的.

**Comment by onewe** [comment]
@hedroid 你可以本地terminal 打开一个tunnel 然后连接本地的就可以了.

**Comment by hedroid** [comment]
多谢回复～多谢多谢

**Comment by tyong920** [comment]
多谢多谢🙏
